server:
    port: 9090
spring:
    application:
        name: book-system
    datasource:
        name: druidDataSource
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/ws-book?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: 2wsx#EDC
            filters: stat,wall,config
            max-active: 50
            initial-size: 10
            max-wait: 60000
            min-idle: 1
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: select 'x'
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-open-prepared-statements: 50
            max-pool-prepared-statement-per-connection-size: 20
    redis:
        host: 127.0.0.1
        password: 2wsx#EDC
        port: 6379
        timeout: 1000
        database: 0
        lettuce:
            pool:
                max-active: 8
                max-wait: -1
                max-idle: 8
                min-idle: 1
    main:
        allow-circular-references: true # 允许循环依赖
    flyway:
        locations: classpath:db/migration
        enabled: true
        baselineOnMigrate: true
token:
    expiration: 7200 #2小时过期
mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
    configuration:
        use-generated-keys: true
        map-underscore-to-camel-case: true

